ENH: Transition project configuration to `pyproject.toml`
InsightSoftwareConsortium/ITKMinimalPathExtraction pull request #105
Opened 2024-06-22 22:38 UTC by jhlegarreta

- ENH: Transition project configuration to `pyproject.toml`
- COMP: Update CI configuration for ITK 5.4

2024-06-22 22:45 UTC, aylward approved these changes
LGTM!

If there are build failures that are unrelated, this can be merged.

2024-06-26 14:43 UTC, thewtex requested changes

2024-06-26 14:43 UTC, thewtex commented on pyproject.toml
> +readme = "README.md"
> pyproject_metadata.ConfigurationError: Readme file not found ("README.md")

-> README.rst

2024-06-26 14:53 UTC, jhlegarreta commented on pyproject.toml
> +readme = "README.md"
:+1:. Changed in a9b5513.

2024-06-27 19:58 UTC, thewtex approved these changes
:sparkler:

2024-06-27 19:58 UTC, merged